"""Auto-fix and pull request creation service.

Orchestrates the full pipeline: use AgentHarness to analyse a bug issue →
generate fix → create branch → commit files → open pull request.

Steps ③④⑤ (create branch → commit files → open PR) use the GitHub Contents API.
Steps ①② (RAG locate + LLM fix generation) use AgentHarness with tool-calling.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field

from app.assistant.harness import AgentHarness
from app.core.config import settings
from app.services.github_client import GitHubClient
from app.services.repository_url import RepositoryRef
from app.storage import repository_store


@dataclass
class FixProposal:
    """The result of analysing a bug issue and generating a fix."""

    branch_name: str
    title: str
    pr_body: str
    files: list[FixFileChange] = field(default_factory=list)


@dataclass
class FixFileChange:
    """One file to create or update as part of a fix."""

    path: str
    content: str
    commit_message: str
    sha: str | None = None  # None = new file


@dataclass
class FixResult:
    """Result of attempting an auto-fix."""

    success: bool
    pr_url: str | None = None
    branch_name: str | None = None
    error: str | None = None


class AutoFixService:
    """Analyse a bug issue and create a fix pull request.

    Usage::

        service = AutoFixService()
        result = await service.fix_issue(
            owner="fastapi", name="fastapi",
            issue_number=42,
            issue_title="Crash when saving",
            issue_body="Traceback ...",
            labels=["bug"],
        )
    """

    def __init__(self) -> None:
        self._llm_available = bool(settings.llm_api_key)

    async def fix_issue(
        self,
        owner: str,
        name: str,
        issue_number: int,
        issue_title: str,
        issue_body: str | None,
        labels: list[str],
    ) -> FixResult:
        """Full auto-fix pipeline: analyse → generate → branch → commit → PR."""
        if not self._llm_available:
            return FixResult(success=False, error="LLM is not configured")

        ref = RepositoryRef(owner=owner, name=name)
        branch_name = f"auto-fix/issue-{issue_number}"

        # ── Step ①②: Use AgentHarness to locate files + generate fix ──
        fix_proposal = await self._generate_fix_with_harness(
            owner, name, issue_number, issue_title, issue_body, labels, branch_name,
        )
        if fix_proposal is None or not fix_proposal.files:
            return FixResult(
                success=False,
                branch_name=branch_name,
                error=fix_proposal.pr_body if fix_proposal and fix_proposal.pr_body
                     else "Could not generate fix code.",
            )

        # ── Step ③: Create branch ───────────────────────────────────
        async with GitHubClient() as gh:
            repo = await gh.get_repository(ref)
            default_branch = repo.get("default_branch") or "main"
            commits = await gh.get_commits(ref, 1)
            if not commits:
                return FixResult(success=False, error="No commits found on default branch.")
            sha = commits[0]["sha"]
            await gh.create_branch(ref, branch_name, sha)

        # ── Step ④: Commit each file change ─────────────────────────
        async with GitHubClient() as gh:
            for change in fix_proposal.files:
                await gh.create_or_update_file(
                    ref, change.path, change.content,
                    commit_message=change.commit_message,
                    branch=branch_name,
                    sha=change.sha,
                )

        # ── Step ⑤: Open pull request ───────────────────────────────
        async with GitHubClient() as gh:
            pr = await gh.create_pull_request(
                ref,
                title=f"fix: {issue_title[:72]}",
                head=branch_name,
                base=default_branch,
                body=f"Closes #{issue_number}\n\n{fix_proposal.pr_body}\n\n"
                     f"_🤖 Auto-generated by IssueScope_",
            )

        return FixResult(success=True, pr_url=pr["html_url"], branch_name=branch_name)

    # ── Step ①②: AgentHarness-based fix generation ─────────────────────

    async def _generate_fix_with_harness(
        self,
        owner: str,
        name: str,
        issue_number: int,
        issue_title: str,
        issue_body: str | None,
        labels: list[str],
        branch_name: str,
    ) -> FixProposal | None:
        """Use AgentHarness to explore the repo and generate a fix.

        The LLM calls tools (search_files, knowledge_graph_search) to
        understand the issue, then outputs a JSON block with file changes.
        """
        snapshot = repository_store.get(owner, name)
        if snapshot is None:
            return FixProposal(branch_name=branch_name, title="", pr_body="Repository not synced yet.", files=[])

        harness = AgentHarness()
        labels_str = ", ".join(labels) if labels else "(none)"
        body_str = issue_body or "(no body provided)"

        messages = [
            {
                "role": "system",
                "content": (
                    "You are a code-fixing assistant for an open-source project. "
                    "A user has reported a bug. Your job is to:\n"
                    "1. Use the available tools to explore the repository and understand the code.\n"
                    "2. Find the root cause of the bug.\n"
                    "3. Generate a fix.\n\n"
                    "After your analysis, output a JSON block at the end of your response:\n"
                    '```json\n'
                    '{\n'
                    '  "title": "fix: short description",\n'
                    '  "pr_body": "explanation of the fix",\n'
                    '  "files": [\n'
                    '    {"path": "src/file.py", "content": "full new file content", '
                    '"commit_message": "fix: what changed"}\n'
                    '  ]\n'
                    '}\n'
                    '```\n'
                    "The JSON must be valid and complete. "
                    "For existing files, include the full updated file content in 'content'. "
                    "I will handle getting the file SHA and committing.\n\n"
                    f"Repository: {snapshot.identity.full_name}\n"
                    "Answer in Chinese."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"## Bug Report\n\n"
                    f"**Title**: {issue_title}\n"
                    f"**Body**: {body_str}\n"
                    f"**Labels**: {labels_str}\n\n"
                    "Please analyse this bug and generate a fix."
                ),
            },
        ]

        final_text, _ = await harness.run(messages, snapshot)
        if not final_text:
            return None

        # Parse the JSON block from the response.
        json_match = re.search(r'```json\s*(\{.*?\})\s*```', final_text, re.DOTALL)
        if not json_match:
            # Try finding any JSON object as fallback.
            json_match = re.search(r'(\{.*?"files"\s*:.*?\})', final_text, re.DOTALL)
        if not json_match:
            return FixProposal(
                branch_name=branch_name, title="",
                pr_body=final_text[:500],
                files=[],
            )

        try:
            data = json.loads(json_match.group(1))
        except json.JSONDecodeError:
            return FixProposal(
                branch_name=branch_name, title="",
                pr_body="Failed to parse fix output.",
                files=[],
            )

        files_raw = data.get("files", [])
        if not files_raw:
            return FixProposal(
                branch_name=branch_name, title=data.get("title", ""),
                pr_body=data.get("pr_body", ""),
                files=[],
            )

        # Resolve SHAs for existing files by fetching current file metadata.
        async with GitHubClient() as gh:
            files: list[FixFileChange] = []
            for f in files_raw:
                path = f.get("path", "")
                content = f.get("content", "")
                commit_msg = f.get("commit_message", f"fix: {issue_title[:60]}")

                # Try to get SHA for existing file.
                sha = None
                try:
                    existing = await gh.get_file_content(ref, path, "main", 1)
                    if existing[0] is not None:
                        # Need SHA from the contents API response.
                        # Use a HEAD request to get it.
                        import base64
                        from urllib.parse import quote
                        encoded_path = quote(path, safe="/")
                        try:
                            payload = await gh._get(
                                f"/repos/{ref.owner}/{ref.name}/contents/{encoded_path}",
                                params={"ref": "main"},
                            )
                            sha = payload.get("sha")
                        except Exception:
                            sha = None
                except Exception:
                    sha = None

                files.append(FixFileChange(
                    path=path, content=content,
                    commit_message=commit_msg, sha=sha,
                ))

        return FixProposal(
            branch_name=branch_name,
            title=data.get("title", f"fix: {issue_title[:72]}"),
            pr_body=data.get("pr_body", issue_title),
            files=files,
        )
